export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USERS = "SET_USERS";

export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";

export const SET_CARTS = "SET_CARTS";
export const ADD_CART = "ADD_CART";
export const SET_CART_COUNT = "SET_CART_COUNT";
export const REMOVE_CART = "REMOVE_CART";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_SIMILAR_PRODUCTS = "SET_SIMILAR_PRODUCTS";

export const SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE";
export const SET_PREV_ROUTE = "SET_PREV_ROUTE";
export const UPDATE_CATEGORY_REDUX = "UPDATE_CATEGORY";
